#parallel jobs and one additional job for second build

version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: echo "First parallel job"
      - run: echo ${CIRCLE_BRANCH}
      - run: echo $CIRCLE_BRANCH
      - run: echo $FIRSTVARIABLE
      - run: $SECONDVARIABLE
      - run: $THIRDVARIABLE
  test:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: echo "Second parallel job"
  third:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: echo "Third job another workflow"
  fourth:
    docker:
      - image: circleci/node:4.8.2-jessie
    steps:
      - checkout
      - run: ps aux > text.txt
      - run: cat text.txt
      
      
workflows:
  version: 2
  first_workflow:
    jobs:
      - build
      - test
  "Second workflow":
    jobs:
      - third
      - fourth:
          requires:
            - third
