#parallel jobs and one additional job for second build

version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: echo "First parallel job"
      - run: echo ${CIRCLE_BRANCH}
      - run: echo $CIRCLE_BRANCH
      - run: echo $FIRSTVARIABLE
      - run: $SECONDVARIABLE
      - run: $THIRDVARIABLE
      - run: 
          command: |-
            echo "TRIGGERER: ${CIRCLE_USERNAME}"
            echo "BUILD_NUMBER: ${CIRCLE_BUILD_NUM}"
            echo "BUILD_URL: ${CIRCLE_BUILD_URL}"
            echo "BRANCH: ${CIRCLE_BRANCH}"
            echo "RUNNING JOB: ${CIRCLE_JOB}"
            echo "JOB PARALLELISM: ${CIRCLE_NODE_TOTAL}"
            echo "CIRCLE_REPOSITORY_URL: ${CIRCLE_REPOSITORY_URL}"
  test:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: echo "Second parallel job"
  third:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: echo "Third job another workflow"
      - run: mkdir workspace_one
      - persist_to_workspace:
          root: workspace_one
          
  fourth:
    docker:
      - image: circleci/node:4.8.2-jessie
    steps:
      - checkout
      - attach_workspace:
          at: workspace_one
      - run: ps aux > text.txt
      - run: cat text.txt
      
      
workflows:
  version: 2
  first_workflow:
    jobs:
      - build
      - test
  "Second workflow":
    jobs:
      - third
      - fourth:
          requires:
            - third
